version: "3.8"

services:
  concertarr:
    build: .
    container_name: concertarr
    ports:
      - "8090:8090"
    volumes:
      - /mnt/homelab:/mnt/homelab   # acesso à biblioteca de shows
      - concertarr_data:/app/data   # config persistente
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo

volumes:
  concertarr_data:
